#!/usr/bin/env node

'use strict';

const path = require('path');

const FastBootServer = require('ember-alt-fastboot-app-server/src/backing-classes/fastboot-server');

const config = {
  distPath: path.join(__dirname, '../'),
  host: '0.0.0.0',
  port: '4200',
  workerCount: 1, // configurable
  buildSandboxGlobals(globals) {
    return Object.assign({}, globals, {
      process
    });
  }
};

const master = new FastBootServer(config);

master.start();
